// USER
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_LOADING = "SET_CURRENT_USER_LOADING";
export const REMOVE_CURRENT_USER_LOADING = "REMOVE_CURRENT_USER_LOADING";
export const SET_CURRENT_USER_INFO = "SET_CURRENT_USER_INFO";
export const SET_CURRENT_USER_INFO_LOADING = "SET_CURRENT_USER_INFO_LOADING";
export const REMOVE_CURRENT_USER_INFO_LOADING = "REMOVE_CURRENT_USER_INFO_LOADING";
export const CHANGE_USER_ROLE = "CHANGE_USER_ROLE";
export const SET_CHANGE_USER_ROLE_LOADING = "SET_CHANGE_USER_ROLE_LOADING";
export const SET_CHANGE_PASSWORD_LOADING = "SET_CHANGE_PASSWORD_LOADING";
export const GET_RECOMMENDED_PRODUCTS = "GET_RECOMMENDED_PRODUCTS";
export const SET_RECOMMENDED_PRODUCTS_LOADING = "SET_RECOMMENDED_PRODUCTS_LOADING";
export const GET_RECOMMENDED_USERS = "GET_RECOMMENDED_USERS";
export const SET_RECOMMENDED_USERS_LOADING = "SET_RECOMMENDED_USERS_LOADING";
export const GET_RECOMMENDED_VENUES = "GET_RECOMMENDED_VENUES";
export const SET_RECOMMENDED_VENUES_LOADING = "SET_RECOMMENDED_VENUES_LOADING";
export const SET_RESET_PASSWORD_LOADING = "SET_RESET_PASSWORD_LOADING";
export const SET_CHECK_RESET_VALIDITY_LOADING = "SET_CHECK_RESET_VALIDITY_LOADING";
export const SET_RESET_NEW_PASSWORD_LOADING = "SET_RESET_NEW_PASSWORD_LOADING";

// USER PROFILE
export const COMPLETE_MY_PROFILE = "COMPLETE_USER_PROFILE";
export const SET_COMPLETE_MY_PROFILE_LOADING = "SET_COMPLETE_USER_PROFILE_LOADING";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const SET_USER_PROFILE_LOADING = "SET_USER_PROFILE_LOADING";
export const GET_MY_PROFILE = "GET_MY_PROFILE";
export const SET_MY_PROFILE_LOADING = "SET_MY_PROFILE_LOADING";

// ERRORS
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// SHOP
export const GET_SHOP_ITEMS = "GET_SHOP_ITEMS";
export const SET_SHOP_ITEMS_LOADING = "SET_SHOP_ITEMS_LOADING";
export const GET_SHOP_ITEM = "GET_SHOP_ITEM";
export const SET_SHOP_ITEM_LOADING = "SET_SHOP_ITEM_LOADING";
export const EDIT_SHOP_ITEM = "EDIT_SHOP_ITEM";
export const SET_EDIT_SHOP_ITEM_LOADING = "SET_EDIT_SHOP_ITEM_LOADING";
export const DELETE_SHOP_ITEM = "DELETE_SHOP_ITEM";
export const SET_DELETE_SHOP_ITEM_LOADING = "SET_DELETE_SHOP_ITEM_LOADING";
export const SET_CREATE_ITEM_LOADING = "SET_CREATE_ITEM_LOADING";
export const SORT_SHOP_BY_PRICE = "SORT_SHOP_BY_PRICE";
export const SORT_SHOP_BY_NAME = "SORT_SHOP_BY_NAME";
export const SORT_SHOP_BY_RATING = "SORT_SHOP_BY_RATING";
export const REMOVE_ALL_SHOP_ITEMS = "REMOVE_ALL_SHOP_ITEMS";
export const SET_REVIEW_SHOP_ITEM_LOADING = "SET_REVIEW_SHOP_ITEM_LOADING";
export const REVIEW_SHOP_ITEM = "REVIEW_SHOP_ITEM";
export const SAVE_SHOP_ITEM_FROM_LIST = "SAVE_SHOP_ITEM_FROM_LIST";
export const SAVE_SHOP_ITEM_FROM_SINGLE = "SAVE_SHOP_ITEM_FROM_SINGLE";
export const GET_FILTERED_SHOP_ITEMS = "GET_FILTERED_SHOP_ITEMS";

// PRODUCT CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_CART_ITEMS_ON_LOAD = "GET_CART_ITEMS_ON_LOAD";
export const INCREASE_CART_ITEM_QUANTITY = "INCREASE_CART_ITEM_QUANTITY";
export const DECREASE_CART_ITEM_QUANTITY = "DECREASE_CART_ITEM_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const SET_COMPLETE_PURCHASE_LOADING = "COMPLETE_PURCHASE_LOADING";

// PRODUCT ORDER
export const GET_ORDER_ITEMS = "GET_ORDER_ITEMS";
export const SET_ORDER_ITEMS_LOADING = "SET_ORDER_ITEMS_LOADING";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SET_ALL_USERS_LOADING = "SET_ALL_USERS_LOADING";
export const GET_MY_ORDERS = "GET_MY_ORDERS";
export const SET_MY_ORDERS_LOADING = "SET_MY_ORDERS_LOADING";

// POST
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const SET_ALL_POSTS_LOADING = "SET_ALL_POSTS_LOADING";
export const GET_LOCAL_POSTS = "GET_LOCAL_POSTS";
export const SET_LOCAL_POSTS_LOADING = "SET_LOCAL_POSTS_LOADING";
export const GET_A_POST = "GET_A_POST";
export const SET_A_POST_LOADING = "SET_A_POST_LOADING";
export const CREATE_A_POST = "CREATE_A_POST";
export const SET_CREATE_A_POST_LOADING = "SET_CREATE_A_POST_LOADING";
export const REMOVE_ALL_POSTS = "REMOVE_ALL_POSTS";
export const DELETE_POST = "DELETE_POST";
export const SET_DELETE_POST_LOADING = "SET_DELETE_POST_LOADING";

// POST LIKES, COMMENTS AND SAVES
export const LIKE_A_POST_FROM_LIST = "LIKE_A_POST_FROM_LIST";
export const LIKE_A_POST_FROM_LOCAL_LIST = "LIKE_A_POST_FROM_LOCAL_LIST";
export const LIKE_A_POST_FROM_SINGLE = "LIKE_A_POST_FROM_SINGLE";
export const LIKE_A_POST_FROM_USER_PROFILE = "LIKE_A_POST_FROM_USER_PROFILE";
export const LIKE_A_POST_FROM_MY_PROFILE = "LIKE_A_POST_FROM_MY_PROFILE";
export const SAVE_A_POST_FROM_LIST = "SAVE_A_POST_FROM_LIST";
export const SAVE_A_POST_FROM_LOCAL_LIST = "SAVE_A_POST_FROM_LOCAL_LIST";
export const SAVE_A_POST_FROM_SINGLE = "SAVE_A_POST_FROM_SINGLE";
export const SAVE_A_POST_FROM_USER_PROFILE = "SAVE_A_POST_FROM_USER_PROFILE";
export const SAVE_A_POST_FROM_MY_PROFILE = "SAVE_A_POST_FROM_MY_PROFILE";
export const ADD_COMMENT = "ADD_COMMENT";
export const SET_ADD_COMMENT_LOADING = "ADD_COMMENT_LOADING";

// VENUES
export const GET_ALL_VENUES = "GET_ALL_VENUES";
export const REMOVE_ALL_VENUES = "REMOVE_ALL_VENUES";
export const SET_CREATE_VENUE_LOADING = "SET_CREATE_VENUE_LOADING";
export const SET_VENUES_LOADING = "SET_VENUES_LOADING";
export const SORT_VENUE_BY_NAME = "SORT_VENUE_BY_NAME";
export const GET_VENUE = "GET_VENUE";
export const SET_VENUE_LOADING = "SET_VENUE_LOADING";
export const SET_EDIT_VENUE_LOADING = "SET_EDIT_VENUE_LOADING";
export const GET_VENUE_AVAILABILITY = "GET_VENUE_AVAILABILITY";
export const SET_VENUE_AVAILABILITY_LOADING = "SET_VENUE_AVAILABILITY_LOADING";
export const UPDATE_VENUE_SCHEDULE = "UPDATE_VENUE_SCHEDULE";
export const SET_UPDATE_VENUE_SCHDULE_LOADING = "SET_UPDATE_VENUE_SCHDULE_LOADING";
export const VERIFY_VENUE = "VERIFY_VENUE";
export const SET_VERIFY_VENUE_LOADING = "SET_VERIFY_VENUE_LOADING";
export const REVIEW_VENUE = "REVIEW_VENUE";
export const SET_REVIEW_VENUE_LOADING = "SET_REVIEW_VENUE_LOADING";
export const SAVE_VENUE_FROM_LIST = "SAVE_VENUE_FROM_LIST";
export const SAVE_VENUE_FROM_SINGLE = "SAVE_VENUE_FROM_SINGLE";
export const SET_BOOK_VENUE_LOADING = "SET_BOOK_VENUE_LOADING";
export const GET_MY_BOOKINGS = "GET_MY_BOOKINGS";
export const SET_MY_BOOKINGS_LOADING = "SET_MY_BOOKINGS_LOADING";

// MY VENUES
export const GET_MY_VENUES = "GET_MY_VENUES";
export const SET_MY_VENUES_LOADING = "SET_MY_VENUES_LOADING";
export const GET_VENUE_HISTORY = "GET_VENUE_HISTORY";
export const SET_VENUE_HISTORY_LOADING = "SET_VENUE_HISTORY_LOADING";
export const GET_MY_VENUE_AGGREGATES = "GET_MY_VENUE_AGGREGATES";
export const SET_MY_VENUE_AGGREGATES_LOADING = "SET_MY_VENUE_AGGREGATES_LOADING";

// CHAT
export const GET_ALL_CONVERSATIONS = "GET_CONVERSATIONS";
export const SET_ALL_CONVERSATIONS_LOADING = "SET_ALL_CONVERSATIONS_LOADING";
export const GET_CONVERSATION_MESSAGES = "GET_CONVERSATION_MESSAGES";
export const SET_CONVERSATION_MESSAGES_LOADING = "SET_CONVERSATION_MESSAGES_LOADING";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_ARRIVED_MESSAGE = "SET_ARRIVED_MESSAGE";
export const SET_SEND_MESSAGE_LOADING = "SET_SEND_MESSAGE_LOADING";
export const GET_FOLLOWED_USERS = "GET_FOLLOWED_USERS";
export const SET_FOLLOWED_USERS_LOADING = "SET_FOLLOWED_USERS_LOADING";
export const GET_CREATE_CONVERSATION = "GET_CREATE_CONVERSATION";
export const SET_GET_CREATE_CONVERSATION_LOADING = "SET_GET_CREATE_CONVERSATION_LOADING";

// NOTIFICATIONS
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const SET_NOTIFICATIONS_LOADING = "SET_NOTIFICATIONS_LOADING";
export const READ_ALL_NOTIFICATIONS = "READ_ALL_NOTIFICATIONS";
export const READ_A_NOTIFICATION = "READ_A_NOTIFICATION";

// SAVED
export const GET_SAVED = "GET_SAVED";
export const SET_SAVED_LOADING = "SET_SAVED_LOADING";

// FRIENDS
export const GET_FRIENDS = "GET_FRIENDS";
export const SET_FRIENDS_LOADING = "SET_FRIENDS_LOADING";
export const GET_FRIEND_REQUESTS = "GET_FRIEND_REQUESTS";
export const SET_FRIEND_REQUESTS_LOADING = "SET_FRIEND_REQUESTS_LOADING";
export const GET_SENT_REQUESTS = "GET_SENT_REQUESTS";
export const SET_SENT_REQUESTS_LOADING = "SET_SENT_REQUESTS_LOADING";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const SET_ACCEPT_FRIEND_REQUEST_LOADING = "SET_ACCEPT_FRIEND_REQUEST_LOADING";
export const REMOVE_FRIEND = "REMOVE_FRIEND";
export const SET_REMOVE_FRIEND_LOADING = "SET_REMOVE_FRIEND_LOADING";
export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
export const SET_SEND_FRIEND_REQUEST_LOADING = "SET_SEND_FRIEND_REQUEST_LOADING";

// CHALLENGES
export const GET_CHALLENGES = "GET_CHALLENGES";
export const SET_CHALLENGES_LOADING = "SET_CHALLENGES_LOADING";
export const ACCEPT_CHALLENGE = "ACCEPT_CHALLENGE";
export const SET_ACCEPT_CHALLENGE_LOADING = "SET_ACCEPT_CHALLENGE_LOADING";
export const SET_ACCEPTING_CHALLENGE_ID = "SET_ACCEPTING_CHALLENGE_ID";
